name: Send Email

on:
  push:
    branches:
      - main

jobs:
  send-email:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install pip dependencies
        run: |
          python -m pip install --upgrade pip
          pip install secure-smtplib

      - name: Send email
        run: |
          python send_email.py
        env:
          SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SMTP_USERNAME: ${{ secrets.SMTP_USERNAME }}
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
          EMAIL_FROM: 'sender@example.com'
          EMAIL_TO: 'recipient@example.com'
          EMAIL_SUBJECT: 'Test Email'
          EMAIL_BODY: 'This is a test email sent from GitHub Actions.'
